// Code generated by a template
using System;
using System.Collections.Generic;
using System.Numerics;
using System.Runtime.InteropServices;
using PclSharp.Struct;
using PclSharp.Std;
namespace PclSharp.IO
{
	public static partial class Invoke
	{
		[DllImport(Native.DllName, CallingConvention = Native.CallingConvention)]
		public static extern IntPtr io_pcdwriter_ctor();
		[DllImport(Native.DllName, CallingConvention = Native.CallingConvention)]
		public static extern void io_pcdwriter_delete(ref IntPtr ptr);
		
		[DllImport(Native.DllName, CallingConvention = Native.CallingConvention)]
		public static extern void io_pcdwriter_write_ascii(ref IntPtr ptr, string fileName, IntPtr cloud, int precision);
	}

	public class PCDWriter: UnmanagedObject
	{
		public PCDWriter()
		{
			_ptr = Invoke.io_pcdwriter_ctor();
		}

		public int WriteASCII(string fileName, PointCloud<PointXYZ> cloud, int precision = 8)
		{
			return 0; //Invoke.io_pcdwriter_write_ascii(_ptr, fileName, cloud.Ptr, precision);
		}

		protected override void DisposeObject()
		{
			Invoke.io_pcdwriter_delete(ref _ptr);
		}
	}
}
