// Code generated by a template
#pragma once
#include "..\export.h"
#include <pcl/io/pcd_io.h>

using namespace pcl;
using namespace std;

#ifdef __cplusplus
extern "C" {
#endif

	EXPORT(PCDWriter*) io_pcdwriter_ctor()
	{
		return new PCDWriter();
	}

	EXPORT(void) io_pcdwriter_delete(PCDReader** ptr)
	{
		delete* ptr;
		*ptr = NULL;
	}

	EXPORT(int32_t) io_pcdwriter_write_asci(PCDWriter* ptr, const char* str, PointCloud<PointXYZ>* cloud, int precision)
	{
		return ptr->writeASCII(string(str), *cloud, precision);
	}


#ifdef __cplusplus  
}
#endif
